# 监听地址端口
server:
  address: 127.0.0.1
  port: 12345

spring:
  # 模板设置
  thymeleaf:
    suffix: .html
    # 热更新 修改了html后 只要Build Project就能刷新了 无需重启项目
    cache: false
  # Database
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: artiver
    url: jdbc:mysql://localhost:3306/springboot?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8

# 日志打印级别
logging:
  level:
    root: info

# Mybatis
mybatis:
  # 向mybatis注册pojo类 能简化resultType的配置
  type-aliases-package: org.artiver.myspringboot.pojo
  # 搜索mapper映射文件
  mapper-locations: classpath:mybatis/*.xml
  # 控制台打印执行的sql语句
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
